---
title: "PredictingStocks_X"
author: "Hair Parra"
date: "May 10, 2020"
output:
  html_document:
    keep_md: yes
    keep_pdf: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      fig.path = "../img/")
```

#  Historical Stocks Data Anlaysis: Forecasting Closing Prices

## Loading packages

```{r Library loading,warning=FALSE,message=FALSE}
library(tidyverse)
library(tidyquant)
library(gridExtra)
library(tibbletime)
library(forecast)
library(itsmr)
library(here)
library(bbmle)
library(tseries)
library(fpp2)
library(ggthemes)
library(readr)
library(xts)
library(reshape)
require(timeDate)
library(png)
knitr::opts_chunk$set(comment=NA,tidy=TRUE)
```

```{r, echo=FALSE}
# Create a new theme
theme_stonks <- function (base_size = 11, base_family = "") {
    theme_bw() %+replace% 
    theme(
      panel.grid.major  = element_line(), 
      panel.background = element_rect(fill = "lightblue"), # element_rect(fill = "black") 
      panel.border = element_rect(color = "lightblue", fill = NA),
      axis.line = element_line(color = "lightblue"),
      axis.ticks = element_line(color = "lightblue"),
      axis.text = element_text(color = "steelblue")
      )
}
```

## Loading the data 

```{r}
stocks_3M <- read_csv("../data_raw/stocks_data_3M.csv")
head(stocks_3M, 10)
```

## Data Preprocessing

Next, extract the columns of interest and convert into time series objects

```{r}
stocks_3M_data <- select(stocks_3M, Date, Close) # extract cols 
dates <- as.POSIXct.Date(stocks_3M_data$Date) # extract dates in POSIXct format
stocks_3M_data.ts <- xts(stocks_3M_data$Close, 
                        order.by = dates) # 7600
str(stocks_3M_data.ts) # inspect the data
```

## Inspecting the data


## Autoplot, ACF and PACF

```{r}
# Plot the same white noice this time as lines  
autoplot(stocks_3M_data.ts) + 
  geom_line(colour="blue")  +
  ggtitle("Stocks closing price historical data (3M)") + 
  theme_stonks() + xlab("Date") + ylab("USD") + geom_point(color="black")
```


```{r}
# ACF
ggAcf(stocks_3M_data.ts) + theme_stonks()
```

```{r}
# PACF 
ggPacf(stocks_3M_data.ts) + theme_stonks()
```


## Estimating the trend 

```{r}
# Estimate various trends
stocks_3M_linear <- tslm(ts(stocks_3M_data.ts)~trend)  
stocks_3M_p4 <- tslm(ts(stocks_3M_data.ts)~trend + I(trend^2) + I(trend^3) + I(trend^4) + I(trend^5) ) # polynomial
stocks_3M_ma21 <- ma(ts(stocks_3M_data.ts), order=5) # moving average
stocks_3M_trends <- data.frame(cbind(Data=stocks_3M_data.ts, 
                        Linear_trend=fitted(stocks_3M_linear),
                        Poly_trend=fitted(stocks_3M_p4),
                        Moving_avg5 = stocks_3M_ma21
                        ))

# transform to xts objects
stocks_3M_linear <- xts(fitted(stocks_3M_linear), order.by = dates)
stocks_3M_p4 <- xts(fitted(stocks_3M_p4), order.by = dates)

# Plot all the trends together 
autoplot(stocks_3M_data.ts, colour="original") + theme_stonks() + 
  geom_line(aes(y=stocks_3M_linear, color="linear"),size=1) + 
  geom_line(aes(y=stocks_3M_p4, color = "O(5) poly"), size=1) + 
  geom_line(aes(y=stocks_3M_ma21, color ="ma21"), size=1)  + 
  scale_color_manual(values = c('original'= 'blue', 
                                'linear' = 'darkblue',
                                'O(5) poly' = 'red', 
                                'ma21'= 'yellow')) + 
  labs(color = 'Trend fit') +  ylab("USD") + 
  ggtitle("Different trend fits for the stocks data") 
```








